# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('origin', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=240)),
                ('rating', models.IntegerField(default=0)),
                ('reviewer', models.CharField(max_length=128)),
                ('coffee_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bean_app.CoffeeProduct')),
            ],
        ),
    ]
