# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bean_app', '0002_auto_20180308_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='favourite_coffee',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='saved_coffees',
            field=models.ManyToManyField(blank=True, to='bean_app.CoffeeBean'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
