# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bean_app', '0003_auto_20180311_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountform',
            name='user',
        ),
        migrations.DeleteModel(
            name='SignupForm',
        ),
        migrations.RemoveField(
            model_name='vendoraccountform',
            name='user',
        ),
        migrations.DeleteModel(
            name='VendorSignupForm',
        ),
        migrations.RemoveField(
            model_name='coffeebean',
            name='t_type',
        ),
        migrations.DeleteModel(
            name='AccountForm',
        ),
        migrations.DeleteModel(
            name='VendorAccountForm',
        ),
    ]
