# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bean_app', '0003_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('location', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('average_rating', models.IntegerField(default=0)),
                ('t_type', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('favourite_coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bean_app.CoffeeBean')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, max_length=240)),
                ('coffee_bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bean_app.CoffeeBean')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bean_app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('business_name', models.CharField(max_length=128)),
                ('url_online_shop', models.URLField()),
                ('address', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('products_in_stock', models.ManyToManyField(to='bean_app.CoffeeBean')),
            ],
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='coffee_product',
        ),
        migrations.DeleteModel(
            name='CoffeeProduct',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
        migrations.AddField(
            model_name='coffeebean',
            name='tags',
            field=models.ManyToManyField(to='bean_app.Tag'),
        ),
    ]
