# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bean_app', '0004_auto_20180208_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeebean',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
