# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bean_app', '0004_auto_20180315_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeebean',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='coffeebean',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='coffeebean',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
