# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bean_app', '0006_auto_20180208_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffeebean',
            options={'ordering': ('average_rating',)},
        ),
    ]
