# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bean_app', '0008_coffeebean_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='lat',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='vendor',
            name='long',
            field=models.FloatField(default=None),
        ),
    ]
