# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bean_app', '0013_auto_20180224_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='lat',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='long',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
