# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bean_app', '0014_auto_20180225_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(max_length=128),
        ),
    ]
