# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bean_app', '0015_auto_20180225_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeebean',
            name='tags',
            field=models.ManyToManyField(related_name='coffee_beans', to='bean_app.Tag'),
        ),
    ]
